server:
  port: 9092


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name : apigateway-service
  cloud:
    gateway:
      routes:
          - id: petproducerModule
            uri: http://localhost:9090/
            predicates:
            - Path=/producer/**
           # filters:
            # - name: CircuitBreaker
             #  args:
              #   name: producer-app-name
               #  fallbackuri : forward:/producerServiceFallBack
          - id: peerconsumerModule
            uri: http://localhost:9091/
            predicates:
            - Path=/consumer/**
           # filters:
            # - name: CircuitBreaker
             #  args:
              #   name: consumer-app-name
               #  fallbackuri : forward:/consumerServiceFallBack
            
